{% set version = "0.15.3" %}

package:
  name: gimmemotifs
  version: {{ version }}

source:
  url: https://github.com/vanheeringen-lab/gimmemotifs/releases/download/{{ version }}/gimmemotifs-{{ version }}.tar.gz
  sha256: bf3d965ba37b7d2758fa7b33cd91c44f7118973c527cc659e19a406d0dd59731

build:
  number: 0
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python<3.9
    - pybedtools
  run:
    - biofluff >=3.0.4
    - configparser
    - dinamo  # [not osx]
    - diskcache
    - feather-format
    - future
    - gadem
    - genomepy >=0.9.0
    - homer
#    - ipywidgets  # Necessary for progress bar in Jupyter notebook
    - jinja2
    - logomaker
    - meme >=5.1.1
    - prosampler
    - pyarrow >=0.16.0
    - pybedtools
    - python-xxhash
    - pyyaml >=3.10
    - qnorm >=0.5
    - scikit-learn >=0.23.2
    - seaborn >=0.11
    - six
    - statsmodels
    - trawler
    - ucsc-bigbedtobed
    - weeder
    - xdg
    - py-xgboost >=1.0.2
    - xxmotif
          
test:
  imports:
    - gimmemotifs

  commands:
    - gimme --help

about:
  home: https://github.com/vanheeringen-lab/gimmemotifs
  license: MIT
  summary: Motif prediction pipeline and various motif-related tools

extra:
  recipe-maintainers:
    - simonvh
  identifiers:
    - biotools:gimmemotifs
